### PR TITLE
Add links to the user's page and the post

### PR DESCRIPTION
**Pull request by mkopinsky**
While using the tool, I found myself wanting to see users' HN post histories, or send someone a link to the post directly.

Thanks for a great tool!

### CODE REVIEW

**Review by seisvelas — APPROVED** [review]

**Comment by seisvelas** [comment]
Cool! I ran it locally and it appears to run just fine.

Screen Shot 2021-06-07 at 10 51 08 p m

Can't find anything vulnerable (well, using `dangerouslySetInnerHTML` with DOMPurify the way we are doing already makes us vulnerable to HTML injection from the Hacker News API itself, but that is my fault, not yours).

Thanks for the contribution. Would you mind if I add you to a "contributors' thank you" section of the README? I can link to your Twitter or linkedin (or whatever you'd like) as well.

**Comment by seisvelas** [comment]
I'll build and deploy this in a bit

**Comment by seisvelas** [comment]
your changes are now live! yay

**Comment by mkopinsky** [comment]
You're welcome to add me to a thank you section if you want to, but you really don't have to. If you do, a link to my GitHub and/or Twitter (username on both is the same) is best.

**Comment by bsimp** [comment]
This is one of the coolest tools I've run across, thanks @seisvelas!  One question on the location field, is there a correct way to enter the value?  I might not be entering a location correctly, or does that field not work?  If it doesn't, and you have the time to fix, I'd love to see how you did it!  I'm just a curious noob that doesn't know how to code, but wants to learn.

**Pull request merged**
